
- name: Deploy Docker container from GitHub image
  hosts: localhost
  vars:
    github_repository: "https://github.com/Sherbertdlc/Jenkins-CI-CD.git"  # GitHub repository containing the Dockerfile
    docker_image_name: "sherbertdlc/myflaskapp:latest"        # Name of the Docker image
    docker_container_name: "charming_dijkstra"  # Name of the Docker container
    docker_port_mapping: "5000:5000"           # Port mapping (host_port:container_port)

  tasks:
    - name: Clone GitHub repository and build Docker image
      git:
        repo: "https://github.com/Sherbertdlc/Jenkins-CI-CD.git"
        dest: "/tmp/jenkins-CI-CD.git"
        version: "main"
      changed_when: false
      register: git_clone_result

    - name: Run Docker container
      docker_container:
        name: "sherbertdlc/myflaskapp:latest"
        image: "sherbertdlc/myflaskapp:latest"
        state: reloaded
        restart_policy: always
        ports: "5000:5000"
