
- name: Deploy Docker container from GitHub image
  hosts: localhost
  vars:
    github_repository: "username/repository"  # GitHub repository containing the Dockerfile
    docker_image_name: "docker-image"        # Name of the Docker image
    docker_container_name: "docker-container"  # Name of the Docker container
    docker_port_mapping: "9000:80"           # Port mapping (host_port:container_port)

  tasks:
    - name: Clone GitHub repository and build Docker image
      git:
        repo: "https://github.com/{{ github_repository }}"
        dest: "/tmp/{{ github_repository }}"
        version: "master"
      changed_when: false
      register: git_clone_result

    - name: Run Docker container
      docker_container:
        name: "{{ docker_container_name }}"
        image: "{{ docker_image_name }}"
        state: reloaded
        restart_policy: always
        ports: "{{ docker_port_mapping }}"
